version: "3.7"

services:
  api:
    container_name: scrumble-api
    image: node:12
    restart: unless-stopped
    volumes:
      - .:/server
    command: sh -c 'cd /server && yarn && yarn start:dev'
    env_file:
      - .env
    environment:
      NODE_ENV: development
      MONGO_URL: mongodb://mongo:27017/scrumble
    ports:
      - 3000
    depends_on:
      - mongo
  
  mongo:
    container_name: scrumble-mongo
    image: mongo:4
    restart: unless-stopped
    volumes:
      - ./volumes/mongodb:/data/db
    ports:
      - 27017


