version: "3.7"

services:
  api:
    container_name: scrumble-api
    image: node:12
    restart: unless-stopped
    volumes:
      - .:/server
    command: sh -c 'cd /server && yarn && yarn start:debug'
    env_file:
      - .env
    environment:
      MONGO_URL: mongodb://mongo:27017/scrumble
    ports:
      - "3000:3000"
      - "9229:9229"
    depends_on:
      - mongo
  
  mongo:
    container_name: scrumble-mongo
    image: mongo:4
    restart: unless-stopped
    volumes:
      - ./volumes/mongodb:/data/db
    ports:
      - "27017:27017"


